import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/lib/theme-provider";
import Header from "@/app/Header";
import "./globals.css";
import "react-big-calendar/lib/css/react-big-calendar.css";
import Script from "next/script";
import { Fjalla_One, Libre_Franklin, Work_Sans } from "next/font/google";

const workSans = Work_Sans({
  weight: "700",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-worksans",
});

const libreFranklin = Libre_Franklin({
  weight: ["700", "400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-libre-franklin",
});

const fjallaOne = Fjalla_One({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-one",
});

export const metadata: Metadata = {
  title: "Meru Test",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        fetchPriority: "low",
        rel: "icon",
        type: "imag/png",
        url: "/favicon.png?v=19",
      },
      // This will make animated favicon on
      {
        rel: "icon",
        type: "image/gif",
        url: "/favicon.gif?v=21",
        fetchPriority: "high",
      },
    ],
  },
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${workSans.variable} ${libreFranklin.variable} ${fjallaOne.variable} font-sans`}
    >
      <head>
        {/*TODO: figure out why taikwind is not importing all classes*/}
        <Script
          src="https://cdn.tailwindcss.com"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={cn("min-h-screen bg-background font-sans antialiased", "")}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
